document.addEventListener("DOMContentLoaded", (event) => {
  gsap.registerPlugin(ScrollTrigger)
  gsap.fromTo(
    ".hero-heading",{
      x:-100,
      opacity:0
    },{
      x:0,
      opacity:1,
      duration:1,
    }
  )
  gsap.fromTo(".hero-paragraph",{
    y:100,
    opacity:0
  },{
    y:0,
    opacity:1,
    duration:1
  })
  gsap.fromTo(".hero-image",{
    x:-100,
    opacity:0,
  },{
    x:0,
    opacity:1,
    duration:1,
  })
  gsap.fromTo(".cta-button",{
    y:100,
    opacity:0,
  },{
    y:0,
    opacity:1,
    duration:1,
  })
     
 })